### ISSUE TITLE
NullPointerException without strategy-property

### ISSUE THREAD

**Issue by tormoseng** [sopeco/DynamicSpotter-Extensions#43]
branch: without-i43-server

If testing OLB-DBO Congestion, you'll receive a NullPointerException if the "strategy" property of DBO Congestion is not set:

SEVERE: Diagnosis failed!
java.lang.NullPointerException
    at org.spotter.ext.detection.dbcongestion.DBCongestionDetectionController.loadProperties(DBCongestionDetectionController.java:70)
    at org.spotter.core.config.interpretation.HierarchyFactory.createPerformanceProblemHierarchy(HierarchyFactory.java:80)
    at org.spotter.core.Spotter.retrieveRootPerformanceProblem(Spotter.java:184)
    at org.spotter.core.Spotter.startDiagnosis(Spotter.java:133)
    at org.spotter.service.SpotterServiceWrapper$1.run(SpotterServiceWrapper.java:127)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by snowball77** [comment]
This reads "just" like a usability glitch that you do not get notified earlier and properly, right?

**Comment by tormoseng** [comment]
I guess it can be solved by making the strategy property a default property.
