### ISSUE TITLE
NoClassDefFoundError at EDCDetectionController

### ISSUE THREAD

**Issue by MarcelTUC** [sopeco/DynamicSpotter-Extensions#51]
#### How to reproduce
- Eclipse with DynamicSpotter-Plugin
- create a new project, set up the DynamicSpotter configuration: "workload.experiment.duration: 60", "workload.maxusers: 100".
- As Instrumentation Satellite Adapter use the "DynamicInstrumentationClient"
- As Measurement Satellite Adapter use the "MeasurementClient"
- As workload I am using JMeter.

Start Dynamic Spotter and the exception occurs.
#### Exception

`org/lpe/common/utils/sql/SQLStringUtils
java.lang.NoClassDefFoundError: org/lpe/common/utils/sql/SQLStringUtils
    at org.spotter.ext.detection.edc.strategies.RelativeQueryRTStrategy.setMeasurementData(RelativeQueryRTStrategy.java:140)
    at org.spotter.ext.detection.edc.EDCDetectionController.analyze(EDCDetectionController.java:126)
    at org.spotter.core.detection.AbstractDetectionController.analyzeProblem(AbstractDetectionController.java:133)
    at org.spotter.core.Spotter.startDiagnosis(Spotter.java:143)
    at org.spotter.service.SpotterServiceWrapper$1.run(SpotterServiceWrapper.java:126)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.lpe.common.utils.sql.SQLStringUtils
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 10 more`

**Comment by MarcelTUC** [comment]
Finally i found the problem.
I am starting the DS-Server out of Eclipse. After importing the complete projects as maven projects (AIM, LPE-Common, DS, DS-Extensions) I forgot to update the projects: right-click project -> maven -> update project.
Now this problem doesn't occur anymore.
